language: python

dist: xenial

python:
    - '3.5'
    - '3.6'
    - '3.7'
    - '3.8'
    - '3.9'
    - 'pypy3'

env:
    - DJANGO="django>=2.2,<2.2.8"
    - DJANGO="django>=2.2,<2.2.17"
    - DJANGO="django>=2.2.8,<3.0"
    - DJANGO="django>=3.0,<3.1"
    - DJANGO="django>=3.1,<3.2"
    - DJANGO="django>=3.2,<3.3"

install:
    - pip install ${DJANGO}
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python manage.py test

matrix:
    exclude:
        - python: "3.5"
          env: DJANGO="django>=3.0,<3.1"
        - python: "3.5"
          env: DJANGO="django>=3.1,<3.2"
        - python: "3.8"
          env: DJANGO="django>=2.2,<2.2.8"
        - python: "3.9"
          env: DJANGO="django>=2.2,<2.2.17"
